export const DEFAULT_PAGE = 1
export const DEFAULT_PAGE_SIZE = 10
export const SHIPPING_CONTAINER_KEYS = ['plastic-l', 'plastic-s', 'foam-l', 'foam-m', 'foam-s'] as const
export const REF_TRUCK_INVOICE = 'truck_invoice'
export const REF_FISH_SALE_INVOICE = 'fish_sale_invoice'
export const REF_FISH_PURCHASE_INVOICE = 'fish_purchase_invoice'
export const PAYMENT_PAID = 'paid'
export const PAYMENT_PENDING = 'pending'
export const PAYMENT_PARTIAL = 'partial'
export const PAYMENT_CANCELLED = 'cancelled'
