// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AllocatePaymentFIFO(arg1) {
  return window['go']['main']['App']['AllocatePaymentFIFO'](arg1);
}

export function ChangeInvoiceStatus(arg1, arg2, arg3) {
  return window['go']['main']['App']['ChangeInvoiceStatus'](arg1, arg2, arg3);
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function CreateContainer(arg1) {
  return window['go']['main']['App']['CreateContainer'](arg1);
}

export function CreateFishPurchaseInvoice(arg1) {
  return window['go']['main']['App']['CreateFishPurchaseInvoice'](arg1);
}

export function CreateFishSaleInvoice(arg1) {
  return window['go']['main']['App']['CreateFishSaleInvoice'](arg1);
}

export function CreateParty(arg1) {
  return window['go']['main']['App']['CreateParty'](arg1);
}

export function CreateTransaction(arg1) {
  return window['go']['main']['App']['CreateTransaction'](arg1);
}

export function CreateTruckInvoice(arg1) {
  return window['go']['main']['App']['CreateTruckInvoice'](arg1);
}

export function DeleteContainers(arg1) {
  return window['go']['main']['App']['DeleteContainers'](arg1);
}

export function DeleteFishSaleInvoices(arg1) {
  return window['go']['main']['App']['DeleteFishSaleInvoices'](arg1);
}

export function DeleteTransactions(arg1) {
  return window['go']['main']['App']['DeleteTransactions'](arg1);
}

export function DownloadUpdate(arg1) {
  return window['go']['main']['App']['DownloadUpdate'](arg1);
}

export function GetContainerSummary() {
  return window['go']['main']['App']['GetContainerSummary']();
}

export function GetContainers(arg1) {
  return window['go']['main']['App']['GetContainers'](arg1);
}

export function GetFishPurchaseInvoices(arg1) {
  return window['go']['main']['App']['GetFishPurchaseInvoices'](arg1);
}

export function GetFishSaleInvoices(arg1) {
  return window['go']['main']['App']['GetFishSaleInvoices'](arg1);
}

export function GetFishTradeInvoiceSummary(arg1) {
  return window['go']['main']['App']['GetFishTradeInvoiceSummary'](arg1);
}

export function GetParties(arg1) {
  return window['go']['main']['App']['GetParties'](arg1);
}

export function GetParty(arg1) {
  return window['go']['main']['App']['GetParty'](arg1);
}

export function GetPaymentsByPartyID(arg1) {
  return window['go']['main']['App']['GetPaymentsByPartyID'](arg1);
}

export function GetShippingInvoicesByPartyID(arg1) {
  return window['go']['main']['App']['GetShippingInvoicesByPartyID'](arg1);
}

export function GetTransactionSummary(arg1, arg2) {
  return window['go']['main']['App']['GetTransactionSummary'](arg1, arg2);
}

export function GetTransactions(arg1) {
  return window['go']['main']['App']['GetTransactions'](arg1);
}

export function GetTruckInvoice(arg1) {
  return window['go']['main']['App']['GetTruckInvoice'](arg1);
}

export function GetTruckInvoices(arg1) {
  return window['go']['main']['App']['GetTruckInvoices'](arg1);
}

export function ListAtCustomer() {
  return window['go']['main']['App']['ListAtCustomer']();
}

export function ListAtStore() {
  return window['go']['main']['App']['ListAtStore']();
}

export function PayInvoice(arg1) {
  return window['go']['main']['App']['PayInvoice'](arg1);
}

export function RollbackPayment(arg1) {
  return window['go']['main']['App']['RollbackPayment'](arg1);
}

export function RunUpdate(arg1) {
  return window['go']['main']['App']['RunUpdate'](arg1);
}

export function UpdateContainer(arg1, arg2) {
  return window['go']['main']['App']['UpdateContainer'](arg1, arg2);
}

export function UpdateFishPurchaseInvoice(arg1, arg2) {
  return window['go']['main']['App']['UpdateFishPurchaseInvoice'](arg1, arg2);
}

export function UpdateFishSaleInvoice(arg1, arg2) {
  return window['go']['main']['App']['UpdateFishSaleInvoice'](arg1, arg2);
}

export function UpdateTransaction(arg1, arg2) {
  return window['go']['main']['App']['UpdateTransaction'](arg1, arg2);
}
