// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {container} from '../models';
import {transaction} from '../models';
import {domain} from '../models';
import {time} from '../models';

export function CreateContainer(arg1:container.CreateContainerInput):Promise<void>;

export function CreateTransaction(arg1:transaction.CreateTransactionInput):Promise<void>;

export function DeleteTransactions(arg1:Array<string>):Promise<void>;

export function GetContainers():Promise<domain.PageResult_fish_internal_domain_Container_>;

export function GetTransactionSummary(arg1:time.Time,arg2:time.Time):Promise<domain.TransactionSummary>;

export function GetTransactions(arg1:domain.TransactionFilter):Promise<domain.PageResult_fish_internal_domain_Transaction_>;

export function UpdateTransaction(arg1:string,arg2:transaction.CreateTransactionInput):Promise<void>;
