// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';
import {updater} from '../models';
import {container} from '../models';
import {invoice} from '../models';
import {party} from '../models';
import {transaction} from '../models';
import {truckinvoice} from '../models';
import {domain} from '../models';
import {time} from '../models';

export function AllocatePaymentFIFO(arg1:dto.PaymentInput):Promise<void>;

export function ChangeInvoiceStatus(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CheckForUpdates():Promise<updater.UpdateInfo>;

export function CreateContainer(arg1:container.CreateContainerInput):Promise<void>;

export function CreateFishPurchaseInvoice(arg1:invoice.CreateFishPurchaseInvoiceInput):Promise<void>;

export function CreateFishSaleInvoice(arg1:invoice.CreateFishSaleInvoiceInput):Promise<void>;

export function CreateParty(arg1:party.CreatePartyInput):Promise<void>;

export function CreateTransaction(arg1:transaction.CreateTransactionInput):Promise<void>;

export function CreateTruckInvoice(arg1:truckinvoice.CreateTruckInvoiceInput):Promise<void>;

export function DeleteContainers(arg1:Array<number>):Promise<void>;

export function DeleteFishSaleInvoices(arg1:Array<string>):Promise<void>;

export function DeleteTransactions(arg1:Array<string>):Promise<void>;

export function DownloadUpdate(arg1:string):Promise<string>;

export function GetContainerSummary():Promise<container.ContainerSummary>;

export function GetContainers(arg1:container.ContainerFilter):Promise<domain.PageResult_fish_internal_domain_container_Container_>;

export function GetFishPurchaseInvoices(arg1:invoice.InvoiceFilter):Promise<domain.PageResult_fish_internal_domain_invoice_FishPurchaseInvoice_>;

export function GetFishSaleInvoices(arg1:invoice.InvoiceFilter):Promise<domain.PageResult_fish_internal_domain_invoice_FishSaleInvoice_>;

export function GetFishTradeInvoiceSummary(arg1:string):Promise<invoice.FishTradeInvoiceSummary>;

export function GetParties(arg1:party.PartyFilter):Promise<domain.PageResult_fish_internal_domain_party_PartyWithDebt_>;

export function GetParty(arg1:string):Promise<dto.PartyDetailDTO>;

export function GetPaymentsByPartyID(arg1:string):Promise<domain.PageResult_fish_internal_domain_payment_Payment_>;

export function GetShippingInvoicesByPartyID(arg1:string):Promise<domain.PageResult_fish_internal_domain_truck_invoice_ShippingInvoice_>;

export function GetTransactionSummary(arg1:time.Time,arg2:time.Time):Promise<transaction.TransactionSummary>;

export function GetTransactions(arg1:transaction.TransactionFilter):Promise<domain.PageResult_fish_internal_domain_transaction_Transaction_>;

export function GetTruckInvoice(arg1:string):Promise<truckinvoice.TruckInvoice>;

export function GetTruckInvoices(arg1:truckinvoice.TruckInvoiceFilter):Promise<domain.PageResult_fish_internal_domain_truck_invoice_TruckInvoice_>;

export function ListAtCustomer():Promise<Array<dto.CustomerWithContainerDTO>>;

export function ListAtStore():Promise<Array<dto.ContainerListDTO>>;

export function PayInvoice(arg1:dto.PayInvoiceInput):Promise<void>;

export function RollbackPayment(arg1:number):Promise<void>;

export function RunUpdate(arg1:string):Promise<void>;

export function UpdateContainer(arg1:number,arg2:container.CreateContainerInput):Promise<void>;

export function UpdateFishPurchaseInvoice(arg1:string,arg2:invoice.CreateFishPurchaseInvoiceInput):Promise<void>;

export function UpdateFishSaleInvoice(arg1:string,arg2:invoice.CreateFishSaleInvoiceInput):Promise<void>;

export function UpdateTransaction(arg1:string,arg2:transaction.CreateTransactionInput):Promise<void>;
