// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateContainer(arg1) {
  return window['go']['main']['App']['CreateContainer'](arg1);
}

export function CreateFishSaleInvoice(arg1) {
  return window['go']['main']['App']['CreateFishSaleInvoice'](arg1);
}

export function CreateParty(arg1) {
  return window['go']['main']['App']['CreateParty'](arg1);
}

export function CreateTransaction(arg1) {
  return window['go']['main']['App']['CreateTransaction'](arg1);
}

export function DeleteContainers(arg1) {
  return window['go']['main']['App']['DeleteContainers'](arg1);
}

export function DeleteFishSaleInvoices(arg1) {
  return window['go']['main']['App']['DeleteFishSaleInvoices'](arg1);
}

export function DeleteTransactions(arg1) {
  return window['go']['main']['App']['DeleteTransactions'](arg1);
}

export function GetContainerSummary() {
  return window['go']['main']['App']['GetContainerSummary']();
}

export function GetContainers(arg1) {
  return window['go']['main']['App']['GetContainers'](arg1);
}

export function GetFishSaleInvoices(arg1) {
  return window['go']['main']['App']['GetFishSaleInvoices'](arg1);
}

export function GetParties(arg1) {
  return window['go']['main']['App']['GetParties'](arg1);
}

export function GetTransactionSummary(arg1, arg2) {
  return window['go']['main']['App']['GetTransactionSummary'](arg1, arg2);
}

export function GetTransactions(arg1) {
  return window['go']['main']['App']['GetTransactions'](arg1);
}

export function UpdateContainer(arg1, arg2) {
  return window['go']['main']['App']['UpdateContainer'](arg1, arg2);
}

export function UpdateFishSaleInvoice(arg1, arg2) {
  return window['go']['main']['App']['UpdateFishSaleInvoice'](arg1, arg2);
}

export function UpdateTransaction(arg1, arg2) {
  return window['go']['main']['App']['UpdateTransaction'](arg1, arg2);
}
