// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {transaction} from '../models';
import {domain} from '../models';

export function CreateTransaction(arg1:transaction.CreateTransactionInput):Promise<void>;

export function GetTransactions(arg1:domain.TransactionFilter):Promise<Array<domain.Transaction>>;
